GET http://localhost:3001/produtos


###
POST http://localhost:3001/produtos
content-type: application/json

{
    "nome": "Notebook",
    "descricao": "Notebook Dell Inspiron 15 3000",
    "preco": 3500.00
}

###
PATCH http://localhost:3001/produtos/1
content-type: application/json

{
    "nome": "Notebook Dell Inspiron"
}